parser: babel-eslint
extends: airbnb-base
rules:
  no-underscore-dangle: 0
  no-void: 0
  import/extensions:
    - 'error'
    - 'ignorePackages'
    - {js: 'always'}
  import/prefer-default-export: 1

plugins:
  - ava
  - import
