language: node_js
node_js:
  - "14.18.2"
script:
- npm i
- npm run build
- npm test
- cd example && npm i && npm run build && cd ..

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: ./example/build
    on:
      branch: main

  - provider: npm
    skip_cleanup: true
    email: $NPM_AUTH_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: $NPM_AUTH_EMAIL
    api_key: $NPM_AUTH_TOKEN
    tag: "next"
    on:
      branch: main
      condition: $(head package.json | grep -beta)
