language: node_js
node_js:
  - "14.18.2"
script:
- npm i
- npm run build
- npm test
- cd example && npm i && npm run build && cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./example/build
  on:
    branch: main

branches:
  only:
    - main