name: npm-publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm test

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: build pages
        run: |
          cd example
          npm install
          npm run build
      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: example/build

  deploy-to-npm:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  deploy-to-npm-next:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - name: Check if version is a beta
        id: check_version
        run: |
            VERSION=$(node -p "require('./package.json').version")
            if [[ $VERSION == *"-beta"* ]]; then
            echo "Version is a beta: $VERSION"
            echo "::set-output name=is_beta::true"
            else
            echo "Version is not a beta: $VERSION"
            echo "::set-output name=is_beta::false"
            fi
      - name: Check Commit Author
        id: check_author
        run: |
            AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
            if [ "$AUTHOR_NAME" = "mkkhedawat" ]; then
            echo "Commit made by mkkhedawat"
            echo "::set-output name=authorized::true"
            else
            echo "Commit not made by mkkhedawat"
            echo "::set-output name=authorized::false"
            fi
      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.check_version.outputs.is_beta == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Publish to NPM with Beta Tag
        if: steps.check_version.outputs.is_beta == 'true' && steps.check_author.outputs.authorized == 'true'
        run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
